return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			highlight = { enable = true },
			indent = { enable = true },
			auto_install = true,
			sync_install = false,
			ensure_installed = {
				"bash",
				"go",
				"gomod",
				"gosum",
				"gowork",
				"hcl",
				"html",
				"javascript",
				"jsdoc",
				"json",
				"lua",
				"luadoc",
				"make",
				"markdown",
				"markdown_inline",
				"ruby",
				"scala",
				"terraform",
				"tsx",
				"typescript",
				"xml",
				"yaml",
			},
		})
	end,
}
